name: Tests
on: [push, pull_request]
jobs:
  tests-on:
    name: ${{matrix.go-version}} ${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Configure git for private modules
        env:
          GOPRIVATE: "github.com"
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: git config --global url."https://markbates:${REPO_TOKEN}@github.com".insteadOf "https://github.com"
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Test
        env:
          GOPRIVATE: "github.com/gopherguides"
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          git config --global url."https://markbates:${REPO_TOKEN}@github.com".insteadOf "https://github.com"
          make test
